
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA DEF ID LPAREN RPARENfunction : DEF ID LPAREN params RPAREN COLONparams : params : ID param_tailparam_tail : param_tail : COMMA ID param_tail'
    
_lr_action_items = {'DEF':([0,],[2,]),'$end':([1,11,],[0,-1,]),'ID':([2,4,8,],[3,5,10,]),'LPAREN':([3,],[4,]),'RPAREN':([4,5,6,7,10,12,],[-2,-4,9,-3,-4,-5,]),'COMMA':([5,10,],[8,8,]),'COLON':([9,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function':([0,],[1,]),'params':([4,],[6,]),'param_tail':([5,10,],[7,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> function","S'",1,None,None,None),
  ('function -> DEF ID LPAREN params RPAREN COLON','function',6,'p_function','parser.py',5),
  ('params -> <empty>','params',0,'p_params_empty','parser.py',10),
  ('params -> ID param_tail','params',2,'p_params_nonempty','parser.py',14),
  ('param_tail -> <empty>','param_tail',0,'p_param_tail_empty','parser.py',18),
  ('param_tail -> COMMA ID param_tail','param_tail',3,'p_param_tail_nonempty','parser.py',22),
]
