
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ELSE GT ID IF LBRACE LPAREN NUMBER PRINTF RBRACE RPAREN SEMICOLON STRINGstatement : IF LPAREN condition RPAREN block ELSE blockcondition : ID GT NUMBERblock : LBRACE PRINTF LPAREN STRING RPAREN SEMICOLON RBRACE'
    
_lr_action_items = {'IF':([0,],[2,]),'$end':([1,13,18,],[0,-1,-3,]),'LPAREN':([2,12,],[3,14,]),'ID':([3,],[5,]),'RPAREN':([4,10,15,],[6,-2,16,]),'GT':([5,],[7,]),'LBRACE':([6,11,],[9,9,]),'NUMBER':([7,],[10,]),'ELSE':([8,18,],[11,-3,]),'PRINTF':([9,],[12,]),'STRING':([14,],[15,]),'SEMICOLON':([16,],[17,]),'RBRACE':([17,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'condition':([3,],[4,]),'block':([6,11,],[8,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> IF LPAREN condition RPAREN block ELSE block','statement',7,'p_if_else','parser.py',6),
  ('condition -> ID GT NUMBER','condition',3,'p_condition','parser.py',10),
  ('block -> LBRACE PRINTF LPAREN STRING RPAREN SEMICOLON RBRACE','block',7,'p_block','parser.py',14),
]
